# Generated by Django 5.2.17 on 2026-09-26 21:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('co_autor', models.CharField(blank=True, max_length=150, verbose_name='Coautor')),
                ('sinopse', models.TextField(blank=True, verbose_name='Sinopse')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Visível no catálogo')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livro.categoria', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['nome', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do exemplar')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('emprestado', 'Emprestado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exemplares', to='livro.livro')),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aguardando retirada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada'), ('atendida', 'Em empréstimo'), ('finalizada', 'Devolvido')], default='pendente', max_length=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(blank=True, max_length=250, verbose_name='Motivo da recusa')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_gerenciadas', to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='livro.exemplar')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livro.livro')),
            ],
            options={
                'ordering': ['-criada_em', '-pk'],
                'permissions': [('gerenciar_circulacao', 'Pode gerenciar solicitações e empréstimos')],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('prazo', models.DateField(verbose_name='Prazo de devolução')),
                ('devolvido_em', models.DateTimeField(blank=True, null=True)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livro.exemplar')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimo', to='livro.solicitacao')),
            ],
            options={
                'ordering': ['prazo', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pendente', 'aprovada', 'atendida'])), fields=('leitor', 'livro'), name='pedido_ativo_unico_por_leitor_livro'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['aprovada', 'atendida'])), fields=('exemplar',), name='reserva_ativa_unica_por_exemplar'),
        ),
        migrations.AddConstraint(
            model_name='solicitacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['aprovada', 'atendida', 'finalizada']), _negated=True), ('exemplar__isnull', False), _connector='OR'), name='pedido_aprovado_tem_exemplar'),
        ),
        migrations.AddConstraint(
            model_name='emprestimo',
            constraint=models.UniqueConstraint(condition=models.Q(('devolvido_em__isnull', True)), fields=('exemplar',), name='emprestimo_ativo_unico_por_exemplar'),
        ),
    ]
